### PR TITLE
Lora training add + script for low mem gpu

### PR DESCRIPTION
**Pull request by baochi0212**

### CODE REVIEW

**Comment by bys0318** [comment]
Cool PR, I will verify it in the next few days!

**Comment by baochi0212** [comment]
yeah I sanity check it on llama 3.1 8b and lora results on 1000 step really good, really appreciate the dataset :D

**Comment by bys0318** [comment]
Perhaps there is a missing line: `model = get_peft_model(model, lora_config)`?

**Comment by baochi0212** [comment]
ah yeah =)) I mistakenly remove it in the 2nd commit

**Comment by bys0318** [comment]
Cool~merged!

**Pull request merged**
